// anoop840/end-to-end-ai-native-app/End-to-End-Ai-Native-App-abe9c590d0b9a39301bc24e51dd2618ef037fe4c/src/components/AICreationForm.tsx
'use client';

import React, { useState, FormEvent, useCallback } from 'react';
import Modal from './Modal';
import MultiStepIndicator from './MultiStepIndicator';

// Define the steps for the indicator (UPDATED for the Full Agent Workflow)
const steps = ['Submit Idea', 'AI Planning', 'Review Plan', 'AI Coding', 'Review Code', 'Complete'];

// Interface for the detailed planning output from the Strategist Agent (Phase 1)
interface AiPlanningOutput {
  targetFile: string;
  componentName: string;
  dependencies: string[];
  architecturalPlan: string;
}

// Interface for the expected AI response from the Strategist Agent (Phase 1)
interface AiPlanningResponse {
  message: string;
  plan: AiPlanningOutput; 
}

// Interface for the expected AI response from the Developer Agent (Phase 2)
interface AiCodeResponse {
    message: string;
    codeSnippet: string;
    fileName: string;
}

const AICreationForm: React.FC = () => {
    const [text, setText] = useState<string>('');
    const [currentStep, setCurrentStep] = useState<number>(0);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
    
    // Message from the most recent agent (plan description or code review summary)
    const [aiMessage, setAiMessage] = useState<string>(''); 
    
    // Content to display in the modal (plan text or code snippet)
    const [modalContent, setModalContent] = useState<string>(''); 
    
    // Final code snippet generated by the Developer Agent
    const [finalCodeSnippet, setFinalCodeSnippet] = useState<string>('');
    
    // File name agreed upon in Phase 1
    const [fileName, setFileName] = useState<string>('src/ai-generated-logic.ts'); 
    
    // Full plan object from Phase 1, needed for Phase 2 input
    const [planOutput, setPlanOutput] = useState<AiPlanningOutput | null>(null);
    
    const [error, setError] = useState<string | null>(null);

    const handleResetForm = useCallback(() => {
        setText('');
        setModalContent('');
        setFinalCodeSnippet('');
        setAiMessage('');
        setFileName('src/ai-generated-logic.ts');
        setCurrentStep(0);
        setError(null);
        setPlanOutput(null); 
    }, []);

    // --- PHASE 1: Strategist Agent (Initial Submit) ---
    const handleSubmit = useCallback(async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!text.trim()) return;

        setIsLoading(true);
        setError(null);
        setCurrentStep(1); // AI Planning

        try {
            const response = await fetch('/api/ai', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ prompt: text }),
            });

            const data: AiPlanningResponse = await response.json();

            if (!response.ok) {
                // Critical check for server errors or blocked prompts
                throw new Error((data as any).error || 'AI generation failed');
            }

            // Store results of the Planning Agent
            setPlanOutput(data.plan);
            setAiMessage(data.message);
            setFileName(data.plan.targetFile || 'src/ai-generated-logic.ts');

            // Format the plan for the user review modal
            const planText = `// Proposed Component: ${data.plan.componentName}\n// Target File: ${data.plan.targetFile}\n// Dependencies: ${data.plan.dependencies.length > 0 ? data.plan.dependencies.join(', ') : 'None'}\n\n// ARCHITECTURAL PLAN (Phase 1 Output)\n\n${data.plan.architecturalPlan}`;
            setModalContent(planText);
            
            setCurrentStep(2); // Review Plan
            setIsModalOpen(true);

        } catch (err: any) {
            console.error('API Error (Phase 1):', err);
            setError(err.message || 'An unexpected error occurred during AI planning.');
            setCurrentStep(0); 
        } finally {
            setIsLoading(false);
        }
    }, [text]);

    // --- PHASE 2: Developer Agent (Approve Plan -> Generate Code) ---
    const handleApprovePlan = useCallback(async () => {
        if (!planOutput) return;

        setIsModalOpen(false);
        setIsLoading(true);
        setError(null);
        setCurrentStep(3); // AI Coding

        try {
            const response = await fetch('/api/developer-agent', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ plan: planOutput }), // Send the approved plan to the Developer Agent
            });

            const data: AiCodeResponse = await response.json();

            if (!response.ok) {
                throw new Error((data as any).error || 'Developer Agent failed to generate code.');
            }

            // Store results of the Developer Agent
            setFinalCodeSnippet(data.codeSnippet);
            setAiMessage(data.message);
            setFileName(data.fileName);
            
            // Display the actual code snippet for final review (CodeRabbit/User Simulation)
            setModalContent(data.codeSnippet); 

            setCurrentStep(4); // Review Code
            setIsModalOpen(true);

        } catch (err: any) {
            console.error('API Error (Phase 2):', err);
            setError(err.message || 'The Developer Agent encountered an error during coding.');
            setCurrentStep(2); // Go back to Review Plan if it fails
            setIsModalOpen(false);
        } finally {
            setIsLoading(false);
        }
    }, [planOutput]);

    // --- PHASE 3: Apply Code (Approve Code -> Final Write) ---
    const handleApproveCode = useCallback(async () => {
        setIsModalOpen(false);
        setIsLoading(true);
        setError(null);
        setCurrentStep(5); // Complete

        try {
            // This endpoint simulates the cline/Vercel/kestra deployment
            const response = await fetch('/api/apply-code', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ codeSnippet: finalCodeSnippet, fileName }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to apply code (Phase 3).');
            }

            // On Success: The process is complete.
            
            // Optional: Reset the form after success
            setTimeout(() => {
                handleResetForm();
            }, 3000); 

        } catch (err: any) {
            console.error('Code Application Error (Phase 3):', err);
            setError(err.message || 'Failed to save the code to the file system.');
            setCurrentStep(4); // Go back to Review Code on failure
            setIsModalOpen(true); 
        } finally {
            setIsLoading(false);
        }
    }, [finalCodeSnippet, fileName, handleResetForm]);
    
    // --- Determine Modal Handlers and UI Text ---
    const handleModalApprove = currentStep === 2 ? handleApprovePlan : handleApproveCode;
    
    const approveButtonText = currentStep === 2 
        ? 'Approve Plan & Start Coding (Phase 2)' 
        : 'Approve Code & Apply Changes (Phase 3)';

    const rejectButtonText = currentStep === 2 
        ? 'Reject Plan & Refine'
        : 'Reject Code & Refine';
    
    const modalTitle = currentStep === 2 ? 'Strategist Agent: Review Plan' : 'Developer Agent: Review Code';
    
    const isLoadingText = currentStep === 1 
        ? 'Consulting AI Strategist...' 
        : currentStep === 3
        ? 'Consulting AI Developer...'
        : 'Applying Changes...';
        
    const isComplete = currentStep === 5;
    const isDisabled = isLoading || isModalOpen || isComplete;
    const initialButtonText = text.trim().length > 0 
        ? 'Submit to Strategist Agent (Phase 1)'
        : 'Start Agent Pipeline (Phase 1)';
        
    const buttonText = isComplete ? 'Task Completed' : isLoading ? isLoadingText : initialButtonText;
    
    // --- UI IMPROVEMENT: Input Placeholder ---
    const placeholderText = 'Describe the feature or change you want the AI to generate (e.g., "Add a dark mode toggle to the header").';
    
    return (
        <div className="max-w-xl w-full mx-auto p-6 bg-white dark:bg-zinc-900 rounded-xl shadow-2xl border border-gray-100 dark:border-zinc-800">
            <h2 className="text-3xl font-bold mb-4 text-center text-gray-900 dark:text-zinc-50">AI-Driven Feature Builder</h2>
            
            <MultiStepIndicator steps={steps} currentStep={currentStep} />
            
            {/* Main Form Area */}
            <form onSubmit={handleSubmit} className="space-y-6">
                <textarea
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    placeholder={placeholderText}
                    className={`w-full h-32 p-4 border rounded-xl resize-none focus:outline-none focus:ring-4 focus:ring-opacity-50 dark:bg-zinc-800 dark:text-zinc-50 transition-all duration-300 ${
                        isDisabled 
                        ? 'border-gray-300 dark:border-zinc-700 cursor-not-allowed opacity-70'
                        : 'border-blue-300 dark:border-blue-600 focus:ring-blue-500/50'
                    }`}
                    required
                    disabled={isDisabled}
                />
                <button
                    type="submit"
                    className={`w-full font-extrabold py-3 px-4 rounded-xl shadow-lg transition-all duration-300 flex items-center justify-center space-x-2 ${
                        isDisabled
                            ? 'bg-gray-400 dark:bg-zinc-700 text-gray-600 dark:text-zinc-400 cursor-not-allowed'
                            : 'bg-emerald-500 hover:bg-emerald-600 text-white hover:scale-[1.01] active:scale-[0.99] shadow-emerald-500/50'
                    }`}
                    disabled={isDisabled}
                >
                    {isLoading && (
                        <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 1116 0A8 8 0 014 12z"></path>
                        </svg>
                    )}
                    {buttonText} {/* Use the dynamic button text */}
                </button>
            </form>
            
            {/* Error Message */}
            {error && (
                <div className="mt-4 p-4 bg-red-100 text-red-700 border border-red-400 rounded-xl dark:bg-red-950 dark:text-red-300 dark:border-red-700 text-center">
                    Error: {error}
                </div>
            )}
            
            {/* AI Review Modal */}
            <Modal 
                isOpen={isModalOpen}
                message={aiMessage}
                codeSnippet={modalContent}
                onApprove={handleModalApprove}
                onReject={handleResetForm} 
                onClose={() => setIsModalOpen(false)}
                approveButtonText={approveButtonText}
                rejectButtonText={rejectButtonText}
                modalTitle={modalTitle}
            />
            
            {/* Completion Message */}
            {isComplete && (
                <div className="mt-4 p-4 bg-emerald-100 text-emerald-800 border border-emerald-400 rounded-xl dark:bg-emerald-950 dark:text-emerald-300 dark:border-emerald-700 text-center font-bold">
                    ✅ AI-driven task completed and code applied! Ready for a new task.
                </div>
            )}
        </div>
    );
};

export default AICreationForm;